# Generated by Django 6.0.1 on 2026-02-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория проктов',
                'verbose_name_plural': 'Категории проктов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('customer_name', models.CharField(max_length=300, verbose_name='Заказчик')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('type', models.CharField(max_length=300, verbose_name='Тип проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('preview_image', models.ImageField(storage='media/projects/preview', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение')], max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(verbose_name='Место')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media', models.ImageField(blank=True, null=True, storage='media/projects/content', upload_to='', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ('-order',),
            },
        ),
    ]
