# Generated by Django 6.0.1 on 2026-02-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='preview_image',
            field=models.ImageField(upload_to='media/projects/preview/'),
        ),
        migrations.CreateModel(
            name='ContentBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение')], max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(verbose_name='Место')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/projects/content/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ('-order',),
            },
        ),
        migrations.DeleteModel(
            name='ProjectBlocks',
        ),
    ]
