# Generated by Django 6.0.1 on 2026-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_preview_image_contentblocks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentBlocks',
            new_name='ContentBlock',
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ('order',), 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
