# Generated by Django 6.0.1 on 2026-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_contentblocks_contentblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='first_video_frame',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/content/', verbose_name='Первый кадр видео'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects/content/', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение'), ('video', 'Видео')], max_length=20, verbose_name='Тип'),
        ),
    ]
