# Generated by Django 6.0.1 on 2026-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_contentblock_first_video_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/projects/content/', verbose_name='Медиа'),
        ),
    ]
