# Generated by Django 4.2.28 on 2026-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_contentblock_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='first_video_frame',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Первый кадр видео'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='media',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='projectcategories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='preview_image',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Превью'),
        ),
    ]
