# Generated by Django 4.2.7 on 2026-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_is_published_alter_projectcategories_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategories',
            options={'ordering': ('-created_at',), 'verbose_name': 'Категория проектов', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AddField(
            model_name='projects',
            name='body_html',
            field=models.TextField(blank=True, default='', verbose_name='Body HTML'),
        ),
        migrations.AddField(
            model_name='projects',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='projects',
            name='excerpt',
            field=models.TextField(blank=True, default='', verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='projects',
            name='preview_image_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Preview image alt'),
        ),
        migrations.AddField(
            model_name='projects',
            name='seo_description',
            field=models.CharField(default='', max_length=320, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='projects',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='projects',
            name='seo_robots',
            field=models.CharField(default='index,follow', max_length=32, verbose_name='SEO robots'),
        ),
        migrations.AddField(
            model_name='projects',
            name='seo_title',
            field=models.CharField(default='', max_length=255, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='projectscontentblock',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='projectscontentblock',
            name='media_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Media alt'),
        ),
    ]
