# Generated by Django 4.2.x on 2026-03-09

import re
from html import escape

import nh3
from django.db import migrations


ALLOWED_TAGS = {
    "p",
    "br",
    "strong",
    "em",
    "u",
    "s",
    "blockquote",
    "ul",
    "ol",
    "li",
    "a",
    "hr",
    "h2",
    "h3",
    "h4",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "colgroup",
    "col",
    "figure",
    "img",
    "figcaption",
}
ALLOWED_ATTRIBUTES = {
    "a": {"href", "title", "target"},
    "img": {"src", "alt", "loading", "decoding"},
    "th": {"colspan", "rowspan", "scope"},
    "td": {"colspan", "rowspan", "scope"},
    "col": {"span"},
}
ALLOWED_CLASSES = {"p": {"article__lead"}}
ALLOWED_URL_SCHEMES = {"http", "https", "mailto"}
HTML_TAG_RE = re.compile(r"</?[a-zA-Z][^>]*>")


def looks_like_html_fragment(value):
    return bool(value and HTML_TAG_RE.search(value))


def normalize_legacy_text_to_html(value):
    normalized = (value or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not normalized:
        return ""

    paragraphs = []
    for chunk in re.split(r"\n\s*\n+", normalized):
        lines = [escape(line.strip()) for line in chunk.split("\n") if line.strip()]
        if not lines:
            continue
        paragraphs.append(f"<p>{'<br>'.join(lines)}</p>")

    return "".join(paragraphs)


def sanitize_rich_body_html(value):
    raw_value = (value or "").strip()
    if not raw_value:
        return ""

    html_value = raw_value if looks_like_html_fragment(raw_value) else normalize_legacy_text_to_html(raw_value)

    cleaned = nh3.clean(
        html_value,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        allowed_classes=ALLOWED_CLASSES,
        url_schemes=ALLOWED_URL_SCHEMES,
        clean_content_tags={"script", "style"},
        set_tag_attribute_values={"img": {"loading": "lazy", "decoding": "async"}},
        link_rel="noopener noreferrer",
        strip_comments=True,
    )
    return cleaned.strip()


def migrate_projects_body_html_and_defaults(apps, schema_editor):
    Projects = apps.get_model("projects", "Projects")
    ProjectsContentBlock = apps.get_model("projects", "ProjectsContentBlock")

    for project in Projects.objects.all().iterator():
        title = (project.title or "").strip()

        seo_title = (project.seo_title or "").strip() or title
        seo_description = (project.seo_description or "").strip() or title
        seo_keywords = (project.seo_keywords or "").strip()
        seo_robots = (project.seo_robots or "").strip() or "index,follow"

        html_parts = []
        legacy_blocks = ProjectsContentBlock.objects.filter(
            project_id=project.pk,
            type__in=["text", "heading"],
        ).order_by("order")

        for block in legacy_blocks.iterator():
            block_html = sanitize_rich_body_html(block.text or "")
            if block_html:
                html_parts.append(block_html)

        merged_html = "".join(html_parts).strip()

        project.seo_title = seo_title
        project.seo_description = seo_description
        project.seo_keywords = seo_keywords
        project.seo_robots = seo_robots

        if not (project.excerpt or "").strip():
            project.excerpt = seo_description

        if merged_html and not (project.body_html or "").strip():
            project.body_html = merged_html

        if project.preview_image and not (project.preview_image_alt or "").strip():
            project.preview_image_alt = f"{title or 'Project'} preview image"

        project.save(
            update_fields=[
                "body_html",
                "excerpt",
                "preview_image_alt",
                "seo_title",
                "seo_description",
                "seo_keywords",
                "seo_robots",
            ]
        )

    for block in ProjectsContentBlock.objects.filter(type="image"):
        if not block.media or (block.media_alt or "").strip():
            continue

        project_title = ""
        if block.project_id:
            project_title = (block.project.title or "").strip()
        block.media_alt = f"{project_title or 'Project'} image"
        block.save(update_fields=["media_alt"])

    ProjectsContentBlock.objects.filter(type__in=["text", "heading"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_projectcategories_options_projects_body_html_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_projects_body_html_and_defaults, migrations.RunPython.noop),
    ]
