# Generated by Django 4.2.29 on 2026-04-21 11:46

from django.db import migrations, models
import django.db.models.deletion


SERVICE_PAGE_SLUGS = (
    "service",
    "environment",
    "stand",
    "musium",
    "design",
    "content",
    "app",
)


def create_service_page_project_rows(apps, schema_editor):
    ServicePageProjects = apps.get_model("projects", "ServicePageProjects")
    for slug in SERVICE_PAGE_SLUGS:
        ServicePageProjects.objects.get_or_create(slug=slug)


def delete_service_page_project_rows(apps, schema_editor):
    ServicePageProjects = apps.get_model("projects", "ServicePageProjects")
    ServicePageProjects.objects.filter(slug__in=SERVICE_PAGE_SLUGS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_projectcategories_page_h1_and_seo_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePageProjects",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("service", "Техническое сопровождение и обслуживание"),
                            ("environment", "Доступная среда"),
                            ("stand", "Застройка выставок"),
                            ("musium", "Музеи и интерактивные пространства"),
                            ("design", "Архитектурное проектирование и дизайн"),
                            ("content", "Контент и анимация"),
                            ("app", "Разработка приложений и ПО"),
                        ],
                        unique=True,
                        verbose_name="Страница услуги",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "project_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.projects",
                        verbose_name="Проект 1",
                    ),
                ),
                (
                    "project_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.projects",
                        verbose_name="Проект 2",
                    ),
                ),
                (
                    "project_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.projects",
                        verbose_name="Проект 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница проектов на странице услуги",
                "verbose_name_plural": "Страницы проектов на страницах услуг",
                "ordering": ("slug",),
            },
        ),
        migrations.RunPython(
            create_service_page_project_rows,
            reverse_code=delete_service_page_project_rows,
        ),
    ]
