# Generated by Django 4.2.29 on 2026-05-31 00:00

from django.db import migrations, models


def populate_project_sort_order(apps, schema_editor):
    Projects = apps.get_model("projects", "Projects")
    project_ids = Projects.objects.order_by("-created_at", "-pk").values_list("pk", flat=True).iterator()

    for position, project_id in enumerate(project_ids, start=1):
        Projects.objects.filter(pk=project_id).update(sort_order=position)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_servicepageprojects_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="sort_order",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Порядок",
            ),
        ),
        migrations.RunPython(
            populate_project_sort_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
