# Generated by Django 6.0.1 on 2026-01-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ('order',), 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
