# Generated by Django 6.0.1 on 2026-02-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_options_alter_contentblock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_at',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='image',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/content/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview_image',
            field=models.ImageField(upload_to='media/blog/previews/', verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.articles', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение')], max_length=20, verbose_name='Тип'),
        ),
    ]
