# Generated by Django 6.0.1 on 2026-02-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articles_id_alter_contentblock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview_image',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Превью изображение'),
        ),
        migrations.CreateModel(
            name='ArticlesContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение'), ('video', 'Видео')], max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(verbose_name='Место')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Медиа')),
                ('first_video_frame', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Первый кадр видео')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.articles', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
