# Generated by Django 4.2.x on 2026-02-19

from django.db import migrations, models


def backfill_seo_and_alt_fields(apps, schema_editor):
    Articles = apps.get_model("blog", "Articles")
    ArticlesContentBlock = apps.get_model("blog", "ArticlesContentBlock")

    for article in Articles.objects.all():
        title = (article.title or "").strip()
        excerpt = (article.excerpt or "").strip()

        seo_title = (article.seo_title or "").strip() or title
        seo_description = (article.seo_description or "").strip() or excerpt or title
        seo_keywords = (article.seo_keywords or "").strip()
        seo_robots = (article.seo_robots or "").strip() or "index,follow"

        article.seo_title = seo_title
        article.seo_description = seo_description
        article.seo_keywords = seo_keywords
        article.seo_robots = seo_robots

        if not excerpt:
            article.excerpt = seo_description

        if article.preview_image and not (article.preview_image_alt or "").strip():
            article.preview_image_alt = f"{title or 'Article'} preview image"

        article.save(
            update_fields=[
                "excerpt",
                "preview_image_alt",
                "seo_title",
                "seo_description",
                "seo_keywords",
                "seo_robots",
            ]
        )

    for block in ArticlesContentBlock.objects.filter(type="image"):
        if not block.media:
            continue
        if (block.media_alt or "").strip():
            continue

        article_title = ""
        if block.article_id:
            article_title = (block.article.title or "").strip()
        block.media_alt = f"{article_title or 'Article'} image"
        block.save(update_fields=["media_alt"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_articles_id_alter_articles_preview_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="canonical_url",
            field=models.URLField(blank=True, default="", max_length=1024, verbose_name="Canonical URL"),
        ),
        migrations.AddField(
            model_name="articles",
            name="excerpt",
            field=models.TextField(blank=True, default="", verbose_name="Excerpt"),
        ),
        migrations.AddField(
            model_name="articles",
            name="preview_image_alt",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Preview image alt"),
        ),
        migrations.AddField(
            model_name="articles",
            name="seo_description",
            field=models.CharField(default="", max_length=320, verbose_name="SEO description"),
        ),
        migrations.AddField(
            model_name="articles",
            name="seo_keywords",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="SEO keywords"),
        ),
        migrations.AddField(
            model_name="articles",
            name="seo_robots",
            field=models.CharField(default="index,follow", max_length=32, verbose_name="SEO robots"),
        ),
        migrations.AddField(
            model_name="articles",
            name="seo_title",
            field=models.CharField(default="", max_length=255, verbose_name="SEO title"),
        ),
        migrations.AddField(
            model_name="articles",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="articlescontentblock",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="articlescontentblock",
            name="media_alt",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Media alt"),
        ),
        migrations.RunPython(backfill_seo_and_alt_fields, noop_reverse),
    ]
