# Generated by Django 4.2.x on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_basic_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="body_html",
            field=models.TextField(blank=True, default="", verbose_name="Body HTML"),
        ),
    ]
