# Generated by Django 4.2.x on 2026-03-02

import re
from html import escape

import nh3
from django.db import migrations


ALLOWED_TAGS = {
    "p",
    "br",
    "strong",
    "em",
    "u",
    "s",
    "blockquote",
    "ul",
    "ol",
    "li",
    "a",
    "hr",
    "h2",
    "h3",
    "h4",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "colgroup",
    "col",
    "figure",
    "img",
    "figcaption",
}
ALLOWED_ATTRIBUTES = {
    "a": {"href", "title", "target"},
    "img": {"src", "alt", "loading", "decoding"},
    "th": {"colspan", "rowspan", "scope"},
    "td": {"colspan", "rowspan", "scope"},
    "col": {"span"},
}
ALLOWED_CLASSES = {"p": {"article__lead"}}
ALLOWED_URL_SCHEMES = {"http", "https", "mailto"}
HTML_TAG_RE = re.compile(r"</?[a-zA-Z][^>]*>")


def looks_like_html_fragment(value):
    return bool(value and HTML_TAG_RE.search(value))


def normalize_legacy_text_to_html(value):
    normalized = (value or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not normalized:
        return ""

    paragraphs = []
    for chunk in re.split(r"\n\s*\n+", normalized):
        lines = [escape(line.strip()) for line in chunk.split("\n") if line.strip()]
        if not lines:
            continue
        paragraphs.append(f"<p>{'<br>'.join(lines)}</p>")

    return "".join(paragraphs)


def sanitize_article_body_html(value):
    raw_value = (value or "").strip()
    if not raw_value:
        return ""

    html_value = raw_value if looks_like_html_fragment(raw_value) else normalize_legacy_text_to_html(raw_value)

    cleaned = nh3.clean(
        html_value,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        allowed_classes=ALLOWED_CLASSES,
        url_schemes=ALLOWED_URL_SCHEMES,
        clean_content_tags={"script", "style"},
        set_tag_attribute_values={"img": {"loading": "lazy", "decoding": "async"}},
        link_rel="noopener noreferrer",
        strip_comments=True,
    )
    return cleaned.strip()


def migrate_article_body_html(apps, schema_editor):
    Articles = apps.get_model("blog", "Articles")
    ArticlesContentBlock = apps.get_model("blog", "ArticlesContentBlock")

    for article in Articles.objects.all().iterator():
        text_blocks = ArticlesContentBlock.objects.filter(article_id=article.pk, type="text").order_by("order")
        html_parts = []

        for block in text_blocks.iterator():
            block_html = sanitize_article_body_html(block.text or "")
            if block_html:
                html_parts.append(block_html)

        merged_html = "".join(html_parts).strip()
        if merged_html:
            article.body_html = merged_html
            article.save(update_fields=["body_html"])

    ArticlesContentBlock.objects.filter(type__in=["text", "heading"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_articles_body_html"),
    ]

    operations = [
        migrations.RunPython(migrate_article_body_html, migrations.RunPython.noop),
    ]
