# Generated by Django 4.2.7 on 2026-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_migrate_article_body_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlescontentblock",
            name="type",
            field=models.CharField(
                choices=[("image", "Изображение"), ("video", "Видео")],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
