from __future__ import annotations

import argparse
import hashlib
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable
from urllib.error import HTTPError, URLError
from urllib.parse import urljoin, urlparse, urlunparse
from urllib.request import Request, urlopen


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSS_ROOT = REPO_ROOT / "static" / "css"
DEFAULT_ENTRIES_DIR = DEFAULT_CSS_ROOT / "entries"
DEFAULT_OUTPUT_DIR = DEFAULT_CSS_ROOT
DEFAULT_PUBLIC_ORIGIN = "https://cultnova.ru"
DEFAULT_REMOTE_TIMEOUT_SECONDS = 40
DEFAULT_REMOTE_FETCH_ATTEMPTS = 3
CACHE_DIR = REPO_ROOT / ".cache" / "build_public_css"
GENERATED_HEADER = "/* Generated by tools/build_public_css.py. Do not edit directly. */\n"

IMPORT_PATTERN = re.compile(
    r"""
    @import
    \s+
    (?:
        url\(
            \s*
            (?P<url_quote>["'])?
            (?P<url_target>[^)"']+)
            (?P=url_quote)?
            \s*
        \)
        |
        (?P<plain_quote>["'])
        (?P<plain_target>[^"']+)
        (?P=plain_quote)
    )
    (?P<tail>\s*[^;]*)
    ;
    """,
    re.IGNORECASE | re.VERBOSE,
)

URL_REFERENCE_PATTERN = re.compile(
    r"""
    url\(
        \s*
        (?P<quote>["'])?
        (?P<target>[^)"']+)
        (?P=quote)?
        \s*
    \)
    """,
    re.IGNORECASE | re.VERBOSE,
)


@dataclass(frozen=True)
class SourceRef:
    key: str
    display_name: str
    local_path: Path | None = None
    remote_url: str | None = None


RemoteFetcher = Callable[[str], str]


def _normalize_css(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _read_css(path: Path) -> str:
    return _normalize_css(path.read_text(encoding="utf-8"))


def _normalize_public_origin(public_origin: str) -> str:
    parsed = urlparse(public_origin.strip())
    if not parsed.scheme or not parsed.netloc:
        raise ValueError(f"Public CSS origin must be an absolute URL: {public_origin}")
    return urlunparse((parsed.scheme, parsed.netloc, "", "", "", "")).rstrip("/")


def _is_within_root(path: Path, root_dir: Path) -> bool:
    try:
        path.relative_to(root_dir)
    except ValueError:
        return False
    return True


def _resolve_import_path(current_file: Path, target: str, root_dir: Path) -> Path:
    resolved = (current_file.parent / target).resolve()
    resolved_root_dir = root_dir.resolve()
    if not _is_within_root(resolved, resolved_root_dir):
        raise ValueError(
            f"Local CSS import resolves outside the CSS root: {target} from {current_file}"
        )
    if not resolved.is_file():
        raise FileNotFoundError(f"Imported CSS file not found: {target} from {current_file}")
    return resolved


def _has_url_scheme(value: str) -> bool:
    return bool(urlparse(value).scheme)


def _strip_url_fragment(value: str) -> str:
    parsed = urlparse(value)
    return urlunparse((parsed.scheme, parsed.netloc, parsed.path, parsed.params, parsed.query, ""))


def _decode_remote_body(raw_body: bytes, content_type: str | None) -> str:
    charset = "utf-8"
    if content_type:
        for part in content_type.split(";"):
            item = part.strip()
            if item.lower().startswith("charset="):
                charset = item.split("=", 1)[1].strip() or "utf-8"
                break

    try:
        return _normalize_css(raw_body.decode(charset, errors="replace"))
    except LookupError:
        return _normalize_css(raw_body.decode("utf-8", errors="replace"))


def _fetch_remote_css(url: str) -> str:
    request = Request(
        url,
        headers={
            "User-Agent": "cultnova-backend-css-builder/1.0",
            "Accept": "text/css,*/*;q=0.1",
        },
    )
    cache_key = hashlib.sha256(url.encode("utf-8")).hexdigest()
    cache_path = CACHE_DIR / f"{cache_key}.css"
    last_error: Exception | None = None

    for attempt in range(1, DEFAULT_REMOTE_FETCH_ATTEMPTS + 1):
        try:
            with urlopen(request, timeout=DEFAULT_REMOTE_TIMEOUT_SECONDS) as response:
                status_code = getattr(response, "status", response.getcode())
                if status_code != 200:
                    raise RuntimeError(f"Unexpected HTTP status {status_code} for remote CSS: {url}")
                body = response.read()
                content_type = response.headers.get("Content-Type")
                decoded = _decode_remote_body(body, content_type)
                cache_path.parent.mkdir(parents=True, exist_ok=True)
                cache_path.write_text(decoded, encoding="utf-8", newline="\n")
                return decoded
        except HTTPError as exc:
            last_error = RuntimeError(f"Failed to fetch remote CSS {url}: HTTP {exc.code}")
        except URLError as exc:
            last_error = RuntimeError(f"Failed to fetch remote CSS {url}: {exc.reason}")

        if attempt < DEFAULT_REMOTE_FETCH_ATTEMPTS:
            time.sleep(attempt)

    if cache_path.exists():
        return _normalize_css(cache_path.read_text(encoding="utf-8"))

    if last_error is None:
        raise RuntimeError(f"Failed to fetch remote CSS {url}: unknown error")
    raise last_error


class CssBundler:
    def __init__(
        self,
        *,
        root_dir: Path,
        public_origin: str,
        remote_fetcher: RemoteFetcher | None = None,
    ) -> None:
        self.root_dir = root_dir.resolve()
        self.public_origin = _normalize_public_origin(public_origin)
        self.public_origin_parts = urlparse(self.public_origin)
        self.remote_fetcher = remote_fetcher or _fetch_remote_css
        self.bundle_cache: dict[str, str] = {}

    def bundle_local_file(
        self,
        file_path: Path,
        *,
        stack: tuple[SourceRef, ...] = (),
    ) -> str:
        resolved_path = file_path.resolve()
        return self._bundle_ref(self._make_local_ref(resolved_path), stack=stack)

    def _make_local_ref(self, path: Path) -> SourceRef:
        display_path = path
        if _is_within_root(path, self.root_dir):
            display_path = path.relative_to(self.root_dir)
        return SourceRef(
            key=f"file:{path.as_posix()}",
            display_name=display_path.as_posix(),
            local_path=path,
        )

    def _make_remote_ref(self, url: str) -> SourceRef:
        normalized_url = _strip_url_fragment(url)
        return SourceRef(
            key=f"url:{normalized_url}",
            display_name=normalized_url,
            remote_url=normalized_url,
        )

    def _bundle_ref(self, ref: SourceRef, *, stack: tuple[SourceRef, ...]) -> str:
        if ref.key in self.bundle_cache:
            return self.bundle_cache[ref.key]

        for source in stack:
            if source.key == ref.key:
                cycle = " -> ".join(item.display_name for item in (*stack, ref))
                raise ValueError(f"CSS import cycle detected: {cycle}")

        if ref.local_path is not None:
            source = _read_css(ref.local_path)
        elif ref.remote_url is not None:
            source = self.remote_fetcher(ref.remote_url)
        else:
            raise ValueError(f"Unsupported CSS source reference: {ref}")

        bundled = self._bundle_css_source(source, ref=ref, stack=(*stack, ref))
        self.bundle_cache[ref.key] = bundled
        return bundled

    def _bundle_css_source(
        self,
        source: str,
        *,
        ref: SourceRef,
        stack: tuple[SourceRef, ...],
    ) -> str:
        chunks: list[str] = []
        cursor = 0

        for match in IMPORT_PATTERN.finditer(source):
            chunks.append(self._render_css_segment(source[cursor:match.start()], ref=ref))

            target = (match.group("url_target") or match.group("plain_target") or "").strip()
            tail = (match.group("tail") or "").strip()

            if not target or tail:
                chunks.append(match.group(0))
            else:
                imported_ref = self._resolve_import_ref(ref=ref, target=target)
                if imported_ref is None:
                    chunks.append(match.group(0))
                else:
                    bundled_import = self._bundle_ref(imported_ref, stack=stack).strip()
                    if bundled_import:
                        chunks.append(f"{bundled_import}\n")

            cursor = match.end()

        chunks.append(self._render_css_segment(source[cursor:], ref=ref))
        return "".join(chunks)

    def _render_css_segment(self, chunk: str, *, ref: SourceRef) -> str:
        if not chunk or ref.remote_url is None:
            return chunk
        return self._rewrite_remote_url_references(chunk, base_url=ref.remote_url)

    def _resolve_import_ref(self, *, ref: SourceRef, target: str) -> SourceRef | None:
        stripped_target = target.strip()
        if not stripped_target or stripped_target.startswith("//") or stripped_target.startswith("data:"):
            return None

        if ref.local_path is not None and not stripped_target.startswith("/") and not _has_url_scheme(
            stripped_target
        ):
            local_path = _resolve_import_path(ref.local_path, stripped_target, self.root_dir)
            return self._make_local_ref(local_path)

        remote_url = self._resolve_remote_import_url(ref=ref, target=stripped_target)
        if remote_url is None:
            return None

        return self._make_remote_ref(remote_url)

    def _resolve_remote_import_url(self, *, ref: SourceRef, target: str) -> str | None:
        if target.startswith("/"):
            return urljoin(self.public_origin + "/", target.lstrip("/"))

        if _has_url_scheme(target):
            return _strip_url_fragment(target) if self._is_same_origin_url(target) else None

        if ref.remote_url is None:
            return None

        candidate = urljoin(ref.remote_url, target)
        if not self._is_same_origin_url(candidate):
            return None
        return _strip_url_fragment(candidate)

    def _is_same_origin_url(self, value: str) -> bool:
        parsed = urlparse(value)
        return (
            parsed.scheme.lower() == self.public_origin_parts.scheme.lower()
            and parsed.netloc.lower() == self.public_origin_parts.netloc.lower()
        )

    def _rewrite_remote_url_references(self, css_text: str, *, base_url: str) -> str:
        def replace(match: re.Match[str]) -> str:
            target = (match.group("target") or "").strip()
            if (
                not target
                or target.startswith("#")
                or target.startswith("/")
                or target.startswith("//")
                or target.startswith("data:")
                or _has_url_scheme(target)
            ):
                return match.group(0)

            resolved = urljoin(base_url, target)
            if not self._is_same_origin_url(resolved):
                return match.group(0)

            quote = match.group("quote") or ""
            rewritten_target = self._to_root_relative_url(resolved)
            return f"url({quote}{rewritten_target}{quote})"

        return URL_REFERENCE_PATTERN.sub(replace, css_text)

    @staticmethod
    def _to_root_relative_url(value: str) -> str:
        parsed = urlparse(value)
        rendered = parsed.path or "/"
        if parsed.query:
            rendered += f"?{parsed.query}"
        if parsed.fragment:
            rendered += f"#{parsed.fragment}"
        return rendered


def bundle_css_file(
    file_path: Path,
    *,
    root_dir: Path,
    public_origin: str = DEFAULT_PUBLIC_ORIGIN,
    remote_fetcher: RemoteFetcher | None = None,
    stack: tuple[SourceRef, ...] = (),
) -> str:
    bundler = CssBundler(
        root_dir=root_dir,
        public_origin=public_origin,
        remote_fetcher=remote_fetcher,
    )
    return bundler.bundle_local_file(file_path, stack=stack)


def build_public_css(
    *,
    entries_dir: Path = DEFAULT_ENTRIES_DIR,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
    public_origin: str = DEFAULT_PUBLIC_ORIGIN,
    remote_fetcher: RemoteFetcher | None = None,
) -> list[Path]:
    resolved_entries_dir = entries_dir.resolve()
    resolved_output_dir = output_dir.resolve()

    if not resolved_entries_dir.is_dir():
        raise FileNotFoundError(f"CSS entries directory not found: {resolved_entries_dir}")

    bundler = CssBundler(
        root_dir=resolved_entries_dir.parent,
        public_origin=public_origin,
        remote_fetcher=remote_fetcher,
    )
    built_paths: list[Path] = []

    for entry_path in sorted(resolved_entries_dir.glob("*.css")):
        bundled = bundler.bundle_local_file(entry_path).strip()
        rendered = GENERATED_HEADER
        if bundled:
            rendered += f"{bundled}\n"

        output_path = resolved_output_dir / entry_path.name
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered, encoding="utf-8", newline="\n")
        built_paths.append(output_path)

    return built_paths


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Build public backend CSS files from entry sources by expanding local CSS and "
            "same-origin remote @import rules into fully inlined bundles."
        ),
    )
    parser.add_argument(
        "--entries-dir",
        default=str(DEFAULT_ENTRIES_DIR),
        help="Directory with CSS entry files. Defaults to static/css/entries.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory for built CSS output files. Defaults to static/css.",
    )
    parser.add_argument(
        "--public-origin",
        default=DEFAULT_PUBLIC_ORIGIN,
        help="Public site origin used for resolving root-relative and same-origin remote CSS imports.",
    )
    args = parser.parse_args()

    built_paths = build_public_css(
        entries_dir=Path(args.entries_dir),
        output_dir=Path(args.output_dir),
        public_origin=args.public_origin,
    )
    print(f"Built {len(built_paths)} public CSS file(s).")
    for path in built_paths:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
